---
- name: Check if third replica set member is not active
  fail:
    msg: Replica set not in right state 
  when: > 
    (replica_set_status.members[0].stateStr != "PRIMARY") or 
    (replica_set_status.members[1].stateStr != "SECONDARY") or 
    (replica_set_status.members[2].stateStr == "SECONDARY")
